# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  deploy-storybook-trivia-jam:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npx nx run trivia-jam:build-storybook
      - name: Deploy Storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN_TRIVIA_JAM }} -d dist/storybook/trivia-jam --auto-accept-changes --ci

  deploy-storybook-components:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npx nx run components:build-storybook
      - name: Deploy Storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN_COMPONENTS }} -d dist/storybook/components --auto-accept-changes --ci

  deploy-storybook-little-vigilante:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npx nx run little-vigilante:build-storybook
      - name: Deploy Storybook
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN_LITTLE_VIGILANTE }} -d dist/storybook/components --auto-accept-changes --ci
